version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/Demo"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/Docs"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"