manifest:
  version: 0.13

  projects:
  - name: zephyr
    url: https://github.com/zephyrproject-rtos/zephyr
    revision: v3.5.0
    clone-depth: 1
    west-commands: west-commands.yml

  - name: hal_espressif
    url: https://github.com/zephyrproject-rtos/hal_espressif
    revision: 31fc5758f3507f8f0af00b1dea1a0df7af99bfc0
    path: modules/hal/espressif
    west-commands: west/west-commands.yml
    groups:
    - hal

  self:
    path: .