name: 'Build All Targets'
description: 'Build firmware for all ESP32 targets'

inputs:
  idf-version:
    description: 'ESP-IDF version'
    required: true
    default: 'v5.5.1'

runs:
  using: 'composite'
  steps:
    - name: Build all ESP32 targets
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: ${{ inputs.idf-version }}
        path: 'Firmware'
        command: python ../scripts/build_all.py