name: 'Generate Performance Report'
description: 'Generate performance analysis report'

inputs:
  sha:
    description: 'Git commit SHA'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate performance report
      shell: bash
      run: |
        mkdir -p ci-artifacts
        cat > ci-artifacts/performance_report.md << EOF
        # Mesh-NOW Performance Report
        
        **Build Date:** $(date -u)
        **Commit:** ${{ inputs.sha }}
        **ESP-IDF Version:** v5.5.1
        
        ## Binary Size Analysis
        \`\`\`
        $(idf.py size)
        \`\`\`
        
        ## Top Components by Size
        \`\`\`
        $(idf.py size-components | head -10)
        \`\`\`
        
        ## Memory Layout
        - Flash usage optimized for ESP32 (4MB)
        - RAM usage efficient for real-time mesh operations
        - Component separation for modularity
        EOF